services:
  frontend:
    container_name: frontend-react
    image: frontend-react-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/frontend
      - /frontend/node_modules
    command: npm run dev -- --host
